"""
Seed the demo portal with placeholder PDF files.

Each PDF is a tiny valid PDF containing just a text title. They exist
purely so the agent has something to download - they don't contain
real data.

Run directly:
    python scripts/seed_pdfs.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict, List

# Add parent dir to path so we can use the same PDF generator
sys.path.insert(0, str(Path(__file__).parent.parent))

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
import io


def _generate_placeholder_pdf(title: str, body: str = "") -> bytes:
    """Generate a small valid PDF with the given title and body text.

    Returns the PDF as bytes.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )
    styles = getSampleStyleSheet()
    story = [
        Paragraph(title, styles["Title"]),
        Spacer(1, 0.3 * inch),
        Paragraph(body or "This is a placeholder document for the Legacy Portal demo.", styles["Normal"]),
        Spacer(1, 0.2 * inch),
        Paragraph(
            "<i>Generated by the Legacy Portal Automator's seed script. "
            "This file has no real content - it exists so the agent has "
            "something to download.</i>",
            styles["Italic"],
        ),
    ]
    doc.build(story)
    return buf.getvalue()


def seed_default_pdfs(pdfs_dir: Path, tabs: Dict[str, List[str]]) -> None:
    """Generate any missing PDF files listed in the tabs dict.

    Idempotent: only creates files that don't already exist.
    """
    pdfs_dir.mkdir(parents=True, exist_ok=True)

    created_count = 0
    for tab_name, filenames in tabs.items():
        for fname in filenames:
            fpath = pdfs_dir / fname
            if fpath.exists():
                continue

            # Generate a friendly title from the filename
            # e.g. "invoice_001.pdf" -> "Invoice 001"
            title = (
                fname.replace(".pdf", "")
                .replace("_", " ")
                .strip()
                .title()
            )
            body = (
                f"This document belongs to the '{tab_name}' tab. "
                f"Filename: {fname}"
            )

            pdf_bytes = _generate_placeholder_pdf(title, body)
            fpath.write_bytes(pdf_bytes)
            created_count += 1
            print(f"  created: {fname} ({len(pdf_bytes)} bytes)")

    if created_count == 0:
        print("  all PDFs already exist - nothing to create")
    else:
        print(f"  created {created_count} PDF(s)")


def main():
    """Run as a script - seeds the default PDFs in ./pdfs/"""
    pdfs_dir = Path(__file__).parent.parent / "pdfs"

    # Same tabs as defined in app.py
    tabs = {
        "Invoices": ["invoice_001.pdf", "invoice_002.pdf", "invoice_003.pdf"],
        "Notices": ["notice_welcome.pdf", "notice_policy_update.pdf"],
        "Reports": ["report_q1_2024.pdf", "report_q2_2024.pdf"],
    }

    print(f"Seeding PDFs in {pdfs_dir}...")
    seed_default_pdfs(pdfs_dir, tabs)
    print("Done.")


if __name__ == "__main__":
    main()